#!/usr/bin/env python3
"""Turn Els's Excel word lists into data/woorden.csv for the app.

    python3 tools/importeer.py

Reads every .xlsx in lijsten/ (one file per theme; the file name is the theme
name, e.g. "Thema 5, taak 2.xlsx"). Els's format: one word per row in
column A, nouns written dictionary-style as "afslag, de" or "de praktijk".

Example sentences and pictures are not in her files. They live in
data/aanvulling.csv (woord;voorbeeldzin;afbeelding;niet_als_afleider),
maintained by us and checked by Els. The sentence marks the practised word
with [brackets]. niet_als_afleider lists near-synonyms (premie/zorgpremie)
that would also fit the gap, so they are never offered as a wrong option.

Wrong spellings for the spelling question live in data/spelfouten.csv
(woord;fouten, separated by |). New words get candidates generated by
spelfouten() below; a person then checks the file and removes anything that
is a real Dutch word or sounds different from what the rule intended. Rows
already in the file are never regenerated, so corrections stick.

Standard library only, so it runs on any Mac without installing anything.
"""
import random
import csv
import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIJSTEN = ROOT / 'lijsten'
AANVULLING = ROOT / 'data' / 'aanvulling.csv'
UIT = ROOT / 'data' / 'woorden.csv'
SPELFOUTEN = ROOT / 'data' / 'spelfouten.csv'

NS = '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}'


def column_a(path):
    """All non-empty cells in column A of the first sheet."""
    with zipfile.ZipFile(path) as z:
        shared = []
        if 'xl/sharedStrings.xml' in z.namelist():
            for si in ET.fromstring(z.read('xl/sharedStrings.xml')).iter(NS + 'si'):
                shared.append(''.join(t.text or '' for t in si.iter(NS + 't')))
        sheet = ET.fromstring(z.read('xl/worksheets/sheet1.xml'))
        for cell in sheet.iter(NS + 'c'):
            if not re.fullmatch(r'A\d+', cell.get('r', '')):
                continue
            if cell.get('t') == 'inlineStr':
                text = ''.join(t.text or '' for t in cell.iter(NS + 't'))
            else:
                v = cell.find(NS + 'v')
                if v is None:
                    continue
                text = shared[int(v.text)] if cell.get('t') == 's' else v.text
            text = ' '.join(text.split())
            if text:
                yield text


def split_article(entry):
    """'afslag, de' -> ('afslag', 'de'); 'de praktijk' -> ('praktijk', 'de')."""
    m = re.fullmatch(r'(.+?),\s*(de|het)', entry, re.I)
    if m:
        return m.group(1), m.group(2).lower()
    m = re.fullmatch(r'(de|het)\s+(.+)', entry, re.I)
    if m:
        return m.group(2), m.group(1).lower()
    return entry, ''


# Mistakes Dutch learners actually make, chosen so the misspelling is *not*
# another valid form: no d/t at the end (verbaasd/verbaast are both real and
# sound the same), and no consonant doubling after a long vowel or diphthong
# (vergoeden/vergoedden).
SWAPS = [
    (r'ij', 'ei'), (r'ei', 'ij'), (r'au', 'ou'), (r'ou', 'au'),
    (r'ie', 'i'), (r'ch', 'g'), (r'(?<!n)g(?!$)', 'ch'),
    (r'aa', 'a'), (r'ee', 'e'), (r'oo', 'o'), (r'uu', 'u'),
    (r'([bcdfgklmnprst])\1', r'\1'),
    (r'^v', 'f'), (r'^f', 'v'), (r'^z', 's'), (r'^s(?=[aeiou])', 'z'),
    (r'^([^aeiou]*[aeiou])([bdfklmnprst])$', r'\1\2\2'),  # rem -> remm
]
VOWELS = 'aeiou'


def spelfouten(word, n=3):
    lower = word.lower()
    found = []

    def add(c):
        if c != lower and c not in found:
            found.append(c)

    for pattern, rep in SWAPS:
        if re.search(pattern, lower):
            add(re.sub(pattern, rep, lower, count=1))
    for i in range(1, len(lower) - 1):
        a, b, c = lower[i - 1], lower[i], lower[i + 1]
        before = lower[i - 2] if i >= 2 else ''
        # Single short vowel doubled: vaststellen -> vaaststellen
        if b in 'aou' and a not in VOWELS and c not in VOWELS:
            add(lower[:i] + b + lower[i:])
        # Consonant doubled, only after a single vowel: verzekeren -> verzekkeren
        if b in 'bdfklmnprst' and a in VOWELS and c in VOWELS and before not in VOWELS:
            add(lower[:i] + b + lower[i:])
    rng = random.Random(lower)  # stable per word, so reruns don't reshuffle
    rng.shuffle(found)
    # Last resort for short words: swap two neighbouring letters.
    for i in range(1, len(lower) - 1):
        if len(found) >= n:
            break
        add(lower[:i] + lower[i + 1] + lower[i] + lower[i + 2:])
    picked = found[:n]
    if word[0].isupper():
        picked = [p[0].upper() + p[1:] for p in picked]
    return picked


def load_spelfouten():
    if not SPELFOUTEN.exists():
        return {}
    with SPELFOUTEN.open(encoding='utf-8') as f:
        return {r['woord'].strip(): r['fouten'].strip() for r in csv.DictReader(f, delimiter=';')}


def load_aanvulling():
    if not AANVULLING.exists():
        return {}
    with AANVULLING.open(encoding='utf-8') as f:
        return {r['woord'].strip().lower(): r for r in csv.DictReader(f, delimiter=';')}


def main():
    files = sorted(LIJSTEN.glob('*.xlsx'))
    if not files:
        sys.exit(f'Geen .xlsx-bestanden gevonden in {LIJSTEN}')

    extra = load_aanvulling()
    fouten = load_spelfouten()
    all_words = set()
    rows, missing, new_fouten = [], [], []
    for path in files:
        thema = path.stem
        for entry in column_a(path):
            woord, lidwoord = split_article(entry)
            aanv = extra.get(woord.lower(), {})
            zin = (aanv.get('voorbeeldzin') or '').strip()
            if zin and not re.search(r'\[[^\]]+\]', zin):
                print(f'  let op: zin zonder [haakjes] bij "{woord}"')
            if not zin:
                missing.append(f'{thema}: {woord}')
            all_words.add(woord.lower())
            if woord not in fouten:
                fouten[woord] = '|'.join(spelfouten(woord))
                new_fouten.append(woord)
            rows.append([thema, woord, lidwoord, zin, (aanv.get('afbeelding') or '').strip(), fouten[woord],
                         (aanv.get('niet_als_afleider') or '').strip()])

    # A "misspelling" that is another word from the lists is never wrong.
    for row in rows:
        row[5] = '|'.join(f for f in row[5].split('|') if f and f.lower() not in all_words)

    with UIT.open('w', encoding='utf-8', newline='') as f:
        w = csv.writer(f, delimiter=';', lineterminator='\n')
        w.writerow(['thema', 'woord', 'lidwoord', 'voorbeeldzin', 'afbeelding', 'spelfouten', 'niet_als_afleider'])
        w.writerows(rows)

    with SPELFOUTEN.open('w', encoding='utf-8', newline='') as f:
        w = csv.writer(f, delimiter=';', lineterminator='\n')
        w.writerow(['woord', 'fouten'])
        w.writerows(sorted(fouten.items(), key=lambda kv: kv[0].lower()))

    print(f'{len(rows)} woorden uit {len(files)} lijsten -> {UIT.relative_to(ROOT)}')
    if missing:
        print(f'{len(missing)} woorden nog zonder voorbeeldzin.')
    if new_fouten:
        print(f'{len(new_fouten)} nieuwe woorden in {SPELFOUTEN.relative_to(ROOT)}: controleer de spelfouten.')


if __name__ == '__main__':
    main()
